# Generated by Django 3.0 on 2020-10-26 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_mymodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
